### PR TITLE
RHMAP-12848 use latest release of aerogear-cordova-push

### PR DESCRIPTION
**Pull request by jcesarmobile**
fh-js-sdk got updated to 2.18.1 in main.js

### CODE REVIEW

**Comment by corinnekrych** [comment]
👀

**Comment by corinnekrych** [comment]
@jcesarmobile since we're update to 2.18.1 let's make it explicit here:
https://github.com/jcesarmobile/pushstarter-cordova-app/blob/RHMAP-12848/package.json#L6

**Comment by jcesarmobile** [comment]
done and rebased

**Comment by corinnekrych** [comment]
+1
I'll merge it

**Pull request merged**
