### PR TITLE
RHMAP-8364 Moved Gruntfile.js and package.json to www and some changes

### PR DESCRIPTION
**Pull request by jcesarmobile**
Moved Gruntfile.js and package.json to www and some changes and made some changes on them to make it work inside www.

### CODE REVIEW

**Comment by jcesarmobile** [comment]
@secondsun @danielpassos can you take a look?

**Comment by danielpassos** [comment]
👀

**Comment by secondsun** [comment]
README needs updating.  `npm install` fails with 

```
npm ERR! install Couldn't read dependencies
npm ERR! Linux 4.6.4-301.fc24.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! path /home/summers/Projects/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open '/home/summers/Projects/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/summers/Projects/feedhenry/cordova-templates/pushstarter-cordova-app/npm-debug.log

```

**Comment by jcesarmobile** [comment]
@secondsun good catch, we should update the README.md on all the templates where we have done this change

npm install has to be done from www folder now

**Comment by secondsun** [comment]
@nialldonnellyfh Could you maybe add in a quick how to test/what to look for?  I can deploy the digger change and test locally.

**Comment by danielpassos** [comment]
Tested => http://testing.passos.skunkhenry.com/#/projects/qdxav6uic4unwjuostgqzc2d/apps/qdxav6vnlz2wpau43tndhi6s/details

**Comment by danielpassos** [comment]
👍

**Pull request merged**
