### PR TITLE
Manual rollback for npm dependencies

### PR DESCRIPTION
**Pull request by corinnekrych**
@jcesarmobile mind a review?
cc @edewit, @mmurphy

### CODE REVIEW

**Comment by corinnekrych** [comment]
@matzew this is the rollback we spoke about for 3.13.1

**Comment by jcesarmobile** [comment]
👀

**Comment by jcesarmobile** [comment]
package.json should be on the root, not on www

**Comment by corinnekrych** [comment]
@jcesarmobile Good catch, thanks!
anything else?

**Comment by jcesarmobile** [comment]
LGTM now

**Comment by edewit** [comment]
👍

**Pull request merged**
