### PR TITLE
changing title of the application

### PR DESCRIPTION
**Pull request by matzew**
Done for RHMAP-2969

@edewit mind to merge/reveiw ?

### CODE REVIEW

**Comment by edewit** [comment]
:+1:

**Comment by matzew** [comment]
@jasonmadigan do we need more to get this included in 3.6.?

**Comment by jasonmadigan** [comment]
@matzew yeah, fh-template-apps needs to be rebuilt and fhcap updated. to rebuild, checkout `FH-v3.6.0` of feedhenry/template-config, bump the version - will kick off a job to fetch the latest templates and archive them. Update fhcap with this version/build.

**Comment by matzew** [comment]
@jasonmadigan part1: https://github.com/feedhenry/template-config/pull/86

**Pull request merged**
